name: prueba_mvc
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.7.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    
    cupertino_icons: ^1.0.0
    provider: ^4.3.2+2
    firebase_auth: ^0.18.3
    firebase_core: ^0.5.2
    shared_preferences: ^0.5.12+4
    firebase_database: ^4.3.0
    cloud_firestore: ^0.14.3+1
    google_sign_in: ^4.5.6
    get_it: ^3.1.0
    get: ^3.21.3
    http:
    dio: ^3.0.10

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true



assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages